name: Partytool
version: 1.2.1
main: me.snicser.partytool.Partytool
authors: [Snicser]
description: Private project. Geïnspriteerd door Ex-DDG Developer Snics

commands:
  partytool:
    description: Zet de partytool aan of uit.
